### ISSUE TITLE
Permission error when running scripts 

### ISSUE THREAD

**Issue by equinusocio** [contactlab/yeoman-generators#7]
>  ./scripts/prepare.js
/bin/sh: ./scripts/prepare.js: Permission denied
error Command failed with exit code 126.

**Comment by LasaleFamine** [comment]
`chmod +x ./scripts/prepare.js`

**Comment by equinusocio** [comment]
@LasaleFamine @StefanoMagrassi 
`chmod +x ./scripts/prepare.js` solved the issue.

**Comment by StefanoMagrassi** [comment]
I think that we should avoid running js files as shell scripts and use the node binary, also to be fully compatible with windows OS

**Comment by StefanoMagrassi** [comment]
resolved by #12
